---
sampler: !obj:selene_sdk.samplers.RandomPositionsSampler {
    target_path: /path/to/tabix/indexed/targets.bed.gz, 
    reference_sequence: !obj:selene_sdk.sequences.Genome {
         input_path: /path/to/reference_sequence.fa,
         blacklist_regions: hg19  # only hg19 and hg38, remove if not applicable
     },
    features: !obj:selene_sdk.utils.load_features_list {
        input_path:  /path/to/distinct_features.txt 
    },
    seed: 127,
    output_dir: /path/to/output/ 
    test_holdout: [chr8, chr9],
    validation_holdout: [chr6, chr7],
    sequence_length: 1000,
    center_bin_to_predict: 200,
    feature_thresholds: 0.5,
    save_datasets: []
}
n_steps: 1000 #set according to the number of samples you want to generate
batch_size: 64
n_features: 2002 #set to the number of features in your dataset
...
